version: ~> 1.0
language: node_js
notifications:
  email: false
import:
  - source: travi/.travis-ci:authenticated-semantic-release.yml
before_script: npm ls >/dev/null
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
